.TH BRCM80211 "1" "November 2011" "Debian" "User Commands"
.SH NAME
BRCM80211 \- BRCM80211 initvals section dumper for Broadcom AMBA wlan chipsets
.SH SYNOPSIS
.B brcm80211-ivaldump
[\fIFILE\fR]
.SH DESCRIPTION
BRCM80211 initvals section dumper
.PP
Usage: /tmp/pkg/usr/bin/brcm80211\-ivaldump [FILE]
.SH "SEE ALSO"
.BR b43-asm
.BR b43-dasm
.BR b43-ivaldump
.BR brcm80211-fwconv
.SH AUTHOR
b43-asm has been written by Michael Buesch <mb@bu3sch.de>
.PP
This manual has been written by Stefan Lippers-Hollmann <s.l-h@gmx.de> for 
the Debian project (but may be used by others).
